### ISSUE TITLE
Which dataset did you use and how did you feed 3d volumetric images into the network model

### ISSUE THREAD

**Issue by poornasandur** [sindhura-pv/Glioma#1]
Hi @sindhura-pv 
                   Which dataset was used  for this project. And, how did you input 3D volumetric images into network model.

**Comment by sindhura-pv** [comment]
I used MRI images of grade 3 and 4 glioma affected brains. The images were passed on to the model as 500 X 500 X N dimensional vector, where 500 X 500 is the size of each image and n is the number of images in an MRI sequence.

**Comment by poornasandur** [comment]
ok thanks for reply @sindhura-pv
